### PR TITLE
Add prefixes for maestro 

### PR DESCRIPTION
**Pull request by seongreen**
Add prefix for master
Remove Laser brand

### CODE REVIEW

**Comment by Fivell** [comment]
@seongreen , any reason to delete Laser ? 
If you don't needed you can 
```
 CreditCardValidations.delete_brand(:laser)
```

**Comment by seongreen** [comment]
From 2007 the financial institutions which had issued Laser Cards began to replace them with Visa or MasterCard debit cards. Laser cards were withdrawn from the market on February 28 2014.
https://en.wikipedia.org/wiki/Laser_(debit_card)

**Comment by seongreen** [comment]
So main part of Laser range now using by maestro. Wrong brand detection provide us a problem with 3D-Secure and correct financial transaction flow.

**Comment by Fivell** [comment]
@seongreen , I understand that it doesn't exist, however one of the ideas of this gem is to support validation for both new and old brands. But there are options to exclude and include brands for you personal needs in your project. I would love to see this PR adds new prefixes to maestro, but doesn't delete laser brand from yaml

**Comment by Fivell** [comment]
@seongreen , can you do that?

**Comment by seongreen** [comment]
Hm. I need Laser prefixes for maestro detection. I can save laser but without prefixes.

**Comment by Fivell** [comment]
@seongreen ,  you can save laser prefixes, however remove laser from context of your personal application by putting line  ```CreditCardValidations.delete_brand(:laser)``` to your initializer , that should fix all the issues.

**Comment by seongreen** [comment]
Well, It; good for me, but every guys who want to detect card brand should use this hack. May be move laser to an example of old brand like you did with voyager ?

**Comment by seongreen** [comment]
I show you a real case from our project. Card with prefix 630490 that this gem is detect as LASER did't pass validation, because our bank partner does'n work with Laser brand. When we contacted with client, he sad that it's no Laser but Maestro card.

**Comment by Fivell** [comment]
@seongreen, ok in this case I will release 3.0 because of possible breaking changes. Can you squash you commits and add example to README  with Laser ?

**Comment by seongreen** [comment]
UP

**Comment by Fivell** [comment]
fixes #52

**Pull request merged**
