### PR TITLE
MIR payment card brand support added

### PR DESCRIPTION
**Pull request by 1AdAstra1**
MIR payment system is currently gaining wide support in Russia and its neighbors, so I think it could be useful to support this system 'out of the box' as well instead of configuring it manually each time.

Prefixes taken from: https://en.wikipedia.org/wiki/Payment_card_number#Issuer_identification_number_.28IIN.29

### CODE REVIEW

**Comment by 1AdAstra1** [comment]
@Fivell thanks for the feedback! The only thing is, I am a bit unsure how I can fix the Travis issue. I did not edit any gem-related files (only the YAML configs and documentation), but the server environment seemed to already have a snapshot of the environment for the installation (rails1-4.gemfile.lock), which is getting in the way ( https://travis-ci.org/Fivell/credit_card_validations/jobs/194454527 ). Something tells me that the build should be restarted with a clean working directory, but I do not have access to do that. 

I don't have much work experience with Travis, so any information on how I can fix the issue would be much appreciated, thanks!

**Comment by Fivell** [comment]
@1AdAstra1 , you're right your PR is not related to travis status, I'm just telling that I want to fix build before restarting CI and  merging this

**Comment by 1AdAstra1** [comment]
The only thing I forgot to commit is the new version number. :( I guess, it would need a separate version bump edit?

**Comment by Fivell** [comment]
@1AdAstra1 , will release today later, thanks

**Comment by Fivell** [comment]
@1AdAstra1 ,
```

Pushing gem to https://rubygems.org...
Successfully registered gem: credit_card_validations (3.3.0)
```

**Pull request merged**
