### PR TITLE
Relaxing dependency requirements to support Rails 5

### PR DESCRIPTION
**Pull request by qw4n7y**

### CODE REVIEW

**Comment by Fivell** [comment]
@qw4n7y , unfortunately this can't be merged, dependency should also respect ruby version, because rails5 uses ruby 2.2.2+. that's why build is broken

**Comment by qw4n7y** [comment]
@Fivell , I've added a ruby 2.3 / rails 5.0 environment to the TravisCI. All builds are green

**Comment by Fivell** [comment]
thanks, @qw4n7y , please track master branch (your branch has conflicts with master branch) and squash commits into a single one

**Comment by Fivell** [comment]
also @qw4n7y , why did you remove ruby 2.2+ from travis.yml ? I don't see reasons why not to test agains ruby 2.2

**Comment by qw4n7y** [comment]
Hi, @Fivell ! I've returned ruby 2.2.2 to travis list. Unfortunately I see "Only those with write access to this repository can merge pull requests." on my attempt to manage this pull request.

**Comment by Fivell** [comment]
Hi @qw4n7y , first of all please squash your commits in a single one .

**Comment by qw4n7y** [comment]
Hi @Fivell , hope this helps

**Comment by Fivell** [comment]
@qw4n7y , 👍

**Pull request merged**
