### PR TITLE
Added support for Elo brand

### PR DESCRIPTION
**Pull request by rscardinho**
References for new Elo BIN codes:
https://groups.google.com/forum/#!topic/cielo-magento/no_u0TcpdQg
https://gist.github.com/erikhenrique/5931368#file-bin-cc-md

### CODE REVIEW

**Comment by Fivell** [comment]
@rscardinho, hi, great! Thanks for information and PR. Can you please add more information. 
Link provided by you contains up to 20 bins, where did you get  others? Also, please can you order bins in yml file, like it done for other brands ? Thanks again.

**Comment by Fivell** [comment]
refs #32

**Comment by rscardinho** [comment]
Sure! I'll update the PR description with more infos. Just couldn't find the other `yml` files. Where they are? Also forgot to update the readme file

**Comment by rscardinho** [comment]
Ordered all elo bin codes ;)

**Comment by Fivell** [comment]
@rscardinho , :+1:

**Pull request merged**
